/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bag.glb -T 
Files: bag.glb [11.86MB] > /Users/amansinghkaushik/Documents/Tag In/FinalTagIn/tagin-main/public/models/bag-transformed.glb [1.22MB] (90%)
Author: Puneet Sharma (https://sketchfab.com/Eshi_Nito)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kono-bag-black-e661cd91a81a4d8bac772d842755a073
Title: KONO_Bag Black
*/

import React, { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/bag-transformed.glb')

  const customMaterial = useMemo(() => {
    return new THREE.MeshStandardMaterial({ 
        color: new THREE.Color('#FFB6C1'), // Light Pink
        roughness: 1,
        metalness: 0.1
    });
  }, []);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={customMaterial} />
    </group>
  )
}

useGLTF.preload('/models/bag-transformed.glb')
