/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shape.glb -T 
Files: shape.glb [395.3KB] > /Users/amansinghkaushik/Documents/TagIn_AceHack/tagin-main/public/models/shape-transformed.glb [32.95KB] (92%)
Author: fidavore (https://sketchfab.com/fidavore)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shape-3-1700c9340f324f128202b2ee43f60a2f
Title: Shape 3
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/shape-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/shape-transformed.glb')
