/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shopping_bag.glb -T 
Files: shopping_bag.glb [5.08MB] > /Users/amansinghkaushik/Documents/TagIn_AceHack/tagin-main/public/models/shopping_bag-transformed.glb [507.06KB] (90%)
Author: Christopher.Pool1 (https://sketchfab.com/Christopher.Pool1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shopping-bag-2e70d781b65b4de7aa5c7a294223c1cf
Title: Shopping bag
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/shopping_bag-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} />
    </group>
  )
}

useGLTF.preload('/shopping_bag-transformed.glb')
