/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 watch.glb -T 
Files: watch.glb [14.16MB] > /Users/amansinghkaushik/Documents/Tag In/FinalTagIn/tagin-main/public/models/watch-transformed.glb [1.31MB] (91%)
Author: voxelpoint (https://sketchfab.com/voxelpoint)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/watch-ao-e9d617bbd0834af3b3a69aa712736c93
Title: watch-AO
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/watch-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.lambert34SG1} />
      <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.lambert28SG1} />
      <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.lambert30SG1} />
      <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.lambert32SG1} />
      <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.lambert33SG1} />
      <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.lambert29SG1} />
      <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.lambert31SG1} />
    </group>
  )
}

useGLTF.preload('/models/watch-transformed.glb')
